Algoritmo "conteate10"
Var
   valor, contador, salt :inteiro
Inicio
      contador <- 0
      escreva("Quer contar até qual valor? ")
      leia(valor)
      escreva("De quantos em quantos quer contar? ")
      leia(salt)
      enquanto (contador <= valor) faca
               escreval(contador)
               contador <- contador + salt
      fimenquanto
      escreval("Teminei a contagem")
Fimalgoritmo