Algoritmo "exc10"
Var
   h, l, p2, c, qnt_tinta: real
Inicio
      escreva("Qual a altura em metros da parede? ")
      leia(h)
      escreva("Qual o comprimento em metros da parede? ")
      leia(c)
      p2 <- h*c
      l <- 2
      qnt_tinta <- p2 / l
      escreval("A área a ser pintada é de ", p2, "m2")
      escreval("e a quantidade de tinta necessária será de", qnt_tinta, " L.")
      


Fimalgoritmo